### ISSUE TITLE
info.plist

### ISSUE THREAD

**Issue by macaaw** [fatbobman/ShareData_Demo_For_CoreDataWithCloudKit#1]
Could you include your info.plist file and the entitlements file so that it will compile please?

**Comment by fatbobman** [comment]
sorry. I have fixed it.

**Comment by wunto0716** [comment]
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN""http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict>
<key>items</key>
<array>
<dict>
<key>assets</key>
<array>
<dict>
<key>kind</key>
<string>software-package</string>
<key>url</key>
<string>http://192.168.2.20/test.ipa%3C/string%3E
</dict>
</array>
<key>metadata</key>
<dict>
<key>bundle-identifier</key>
<string>com.XXX.XXX</string>
<key>bundle-version</key>
<string>1.00</string>
<key>kind</key>
<string>software</string>
<key>releaseNotes</key>
<string>測試OTA</string>
<key>title</key>
<string>線上安裝測試</string>
</dict>
</dict>
</array></dict></plist>
